name: ptrace-exec ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install bats
      run: sudo apt-get install bats
    - name: compile
      run: make
    - name: test
      run: make check